export const engineeringProjects = [
  {
    id: "ti-linux-driver",
    title: "Embedded Linux battery-gauge driver",
    context: "Texas Instruments · Summer 2026",
    description: "A Linux kernel driver and companion user-space utility for battery-gauge communication, configuration, telemetry, and firmware programming.",
    image: "/images/projects/ti-linux-driver-architecture.png",
    imageAlt: "Simplified architecture showing a user-space gauge utility communicating through a Linux kernel driver and I2C bus to a battery gauge",
    imageFit: "contain" as const,
    caption: "Simplified architecture · Proprietary details omitted",
    tags: ["Embedded Linux", "C", "I2C", "System Integration"],
    visualLabel: "Linux / I2C",
    problem: "Enable an embedded Linux system to communicate with, configure, monitor, and program TI battery gauges.",
    approach: "Developed a Linux kernel driver and companion user-space utility supporting I2C communication, device configuration, telemetry retrieval, and gauge firmware programming.",
    challenges: ["Integrating kernel-space and user-space software with the hardware interface.", "Supporting device behavior across two battery-gauge platforms."],
    outcome: "Delivered a driver suite that retrieves state of charge, voltage, and temperature and supports firmware programming across two gauge platforms.",
  },
  {
    id: "ti-esd-pcb",
    title: "ESD-protected battery-gauge PCB",
    context: "Texas Instruments · Summer 2026",
    description: "A custom PCB designed and validated in Altium to protect battery-gauge communication during electrostatic discharge events.",
    image: "/images/projects/ti-esd-pcb-render.png",
    imageAlt: "Redacted 3D rendering of the custom ESD-protected battery-gauge PCB",
    imageFit: "contain" as const,
    caption: "Redacted 3D render · Proprietary details omitted",
    tags: ["Altium", "PCB Design", "ESD Protection", "Validation"],
    visualLabel: "PCB / ESD",
    problem: "Maintain reliable gauge data communication when the system encounters electrostatic discharge.",
    approach: "Designed a custom board in Altium, incorporated ESD protection, and validated the design through hardware testing.",
    challenges: ["Integrating protection into the battery-gauge interface.", "Connecting observed hardware behavior to board-level design decisions."],
    outcome: "Maintained reliable battery-gauge data communication during contact-discharge testing exceeding 15 kV.",
  },
  {
    id: "lenovo-senior-design",
    title: "Automated liquid-cooling system testing",
    context: "Lenovo / NC State · Senior Design · In progress",
    description: "A multidisciplinary senior design project developing automated tests for Lenovo Neptune datacenter liquid-cooling systems.",
    image: "/images/projects/lenovo-neptune.png",
    imageAlt: "Lenovo Neptune rack hardware and cooling connections — public product imagery",
    caption: "Lenovo public product imagery · Product context, not the student prototype",
    tags: ["Linux", "Python", "SQLite", "Test Automation"],
    problem: "Develop an automated testing system for liquid cooling in Lenovo enterprise and datacenter server racks.",
    approach: "As Technical Project Manager, I coordinate system engineering efforts across electrical, mechanical, and industrial engineering disciplines in collaboration with Lenovo's manufacturing organization.",
    challenges: ["Coordinating requirements across electrical, mechanical, and industrial engineering disciplines.", "Defining hardware/software interfaces and the system-level test approach."],
    outcome: "Completed sponsor discovery and initial requirements definition; currently developing the system architecture and design plan.",
    outcomeLabel: "Current status",
  },
  {
    id: "embedded-car",
    title: "Autonomous & Wi-Fi-controlled car",
    context: "NC State · Embedded Systems",
    description: "An MSP430-powered vehicle with autonomous navigation, Wi-Fi control, and a redesigned lithium-ion power system.",
    image: "/images/projects/rc-car.jpg",
    imageAlt: "Mason's MSP430-based vehicle with circuit board chassis",
    tags: ["MSP430FR2355", "Embedded C", "PID Control", "Li-ion Power"],
    problem: "Build a vehicle supporting both autonomous navigation and live Wi-Fi control.",
    approach: "Developed low-level firmware for timers, interrupts, and serial communication. Replaced AA batteries with a rechargeable lithium-ion supply and tuned adaptive PID control.",
    challenges: ["Integrating peripherals and debugging hardware using schematics and datasheets.", "Coordinating navigation, communication, and power delivery."],
    outcome: "Completed the combined autonomous and Wi-Fi course on the first attempt. Future improvements include DAC speed control and low-power sleep modes.",
  },
  {
    id: "logic-state-machine",
    title: "LED road-sign state machine",
    context: "NC State · Logic Design",
    description: "Two concurrent finite state machines, built and tested on a breadboard to reproduce a curve-warning sign's flashing patterns.",
    image: "/images/projects/led-sign-breadboard.jpg",
    imageAlt: "Breadboarded digital logic circuit for the LED road-sign project",
    tags: ["Digital Logic", "FSM Design", "CMOS"],
    problem: "Reproduce a curve-warning road sign using sequential digital logic.",
    approach: "Designed and breadboarded two concurrent state machines for user inputs and flashing sequences.",
    challenges: ["Handling asynchronous inputs alongside the flashing sequence.", "Troubleshooting and stabilizing the clock circuit."],
    outcome: "Demonstrated the working circuit. Potential improvements include synchronized hazard patterns and cleaner wire routing.",
    reportHref: "/documents/project-reports/ece-212-led-road-sign-report.pdf",
  },
];

export const additionalVerilogProjects = [
  {
    title: "8x8 Dadda Multiplier",
    context: "ECE 310 · Gate-level Verilog",
    description:
      "A structural multiplier that compresses partial products through staged Dadda reduction before a final ripple-carry addition.",
    tags: ["Structural Verilog", "Arithmetic Circuits", "Testbench Verification"],
    reportHref: "/documents/project-reports/ece-310-dadda-multiplier-report.pdf",
  },
  {
    title: "Dataflow Arithmetic Calculator",
    context: "ECE 310 · Dataflow Verilog",
    description:
      "A controller-and-datapath design combining structural registers, signed arithmetic, capture sequencing, and a delayed valid signal.",
    tags: ["Dataflow Modeling", "Control / Datapath", "2's Complement"],
    reportHref: "/documents/project-reports/ece-310-dataflow-calculator-report.pdf",
  },
  {
    title: "Serial BCD ALU",
    context: "ECE 310 · Behavioral Verilog",
    description:
      "A framed serial arithmetic system with SIPO input, parallel four-digit BCD addition or subtraction, and PISO output.",
    tags: ["Serial Protocols", "BCD Arithmetic", "Finite State Machines"],
    reportHref: "/documents/project-reports/ece-310-serial-bcd-alu-report.pdf",
  },
];
